public enum TokenType {
    VARTYPE,
    RETURN_KEYWORD,
    PRINT_KEYWORD,

    IDENTIFIER,
    NUMBER,

    LEFT_PARENTHESIS, RIGHT_PARENTHESIS,
    LEFT_BRACKET, RIGHT_BRACKET,
    LEFT_BRACE, RIGHT_BRACE,
    COMMA, SEMICOLON, ASSIGN, PLUS, MINUS, STAR, SLASH,

    EOF
}
